#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.kernel/.archi.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.kernel/battery.profile /data/.kernel/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.kernel/balanced.profile /data/.kernel/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.kernel/performance.profile /data/.kernel/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
